# Generated by Django 3.2 on 2022-06-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
